on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Set APP_ENV variable
        if: steps.branch-name.outputs.current_branch == 'main'
        run: |
          echo "export APP_ENV=${{ vars.APP_ENV }}" >> $GITHUB_ENV
      - name: Set APP_ENV variable
        if: steps.branch-name.outputs.current_branch == 'uat'
        run: |
          echo "export APP_ENV=${{ vars.APP_ENV }}" >> $GITHUB_ENV
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
      - name: get variables value
        run: |
          echo "APP_ENV : $APP_ENV"
        env:
          APP_ENV:  ${{ vars.APP_ENV }}
