on:
  push:
    branches:
      - main
      - uat
      
jobs:   
  test_deploy_env:
    runs-on: ubuntu-latest
    name: Testing Env value
    environment: staging
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Get Environment var value
        run: |
         echo "APP_ENV_value : $APP_ENV"
     
      - name: get variables value
        run: |
          echo "APP_ENV : $env.APP_ENV"
        env:
          APP_ENV:  ${{ vars.APP_ENV }}
          
      - name: Get branch name
        run: |
         REF_NAME_UPPER=$(echo "${{ github.ref_name }}" | awk '{print toupper($0)}')
         echo "The current branch is ${{ github.ref_name }} and capital one is ${{ REF_NAME_UPPER}} "

       
        
