on:
  push:
    branches:
      - main
      - uat
      
      
jobs:
  test_deploy_env:
    runs-on: ubuntu-latest
    name: Testing Env value
    environment: staging
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      
      - name: Get Environment var value
        run: |
         echo "APP_ENV_value : $APP_ENV"
     
      - name: get variables value
        run: |
          echo "APP_ENV : $env.APP_ENV"
        env:
          APP_ENV:  ${{ vars.APP_ENV }}
