on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Set environment based on branch
        id: set_environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=environment::production"
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "::set-output name=environment::staging"
          else
            echo "::set-output name=environment::development"
          fi
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: get variables value
        run: |
          echo "APP_ENV : $APP_ENV"
        env:
          APP_ENV:  ${{ vars.APP_ENV }}
