on:
  push:
    branches:
      - main
      - uat

jobs:
  test_deploy_env:
    runs-on: ubuntu-latest
    name: Testing Env value
    environment: staging
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Get Environment var value
        run: |
          echo "APP_ENV_value : $env.APP_ENV"

      - name: Get variables value
        run: |
          echo "APP_ENV : ${{ env.APP_ENV }}"
        env:
          APP_ENV: ${{ env.APP_ENV }}

      - name: Convert branch name to capital
        id: set_ref_name_upper
        run: |
          REF_NAME_UPPER=$(echo "${{ github.ref_name }}" | awk '{print toupper($0)}')
          echo "The current branch is ${{ github.ref_name }} and capital one is $REF_NAME_UPPER"
          echo "REF_NAME_UPPER=$REF_NAME_UPPER" >> $GITHUB_ENV

      - name: Use REF_NAME_UPPER
        run: |
          echo "The capital branch name is ${{ env.REF_NAME_UPPER }}"

  deploy_dev:
    uses: ./.github/workflows/subaction.yaml
    with: 
     environment: dev
     